/**
 * Resolves cover art and track lengths for the playlist.
 *
 * Reads the hand-written list in scripts/playlist.json ({ title, artist, query })
 * and writes src/utils/songs.ts with an artwork URL and duration for each track.
 *
 * Artwork is referenced by URL from Apple's CDN rather than copied into the
 * repo, so no cover images are redistributed here.
 *
 * Run with: node scripts/fetch-artwork.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Seed = { title: string; artist: string; query: string };

const ROOT = join(import.meta.dirname, "..");
const SEEDS: Seed[] = JSON.parse(
  readFileSync(join(ROOT, "scripts/playlist.json"), "utf8"),
);

const ITUNES = "https://itunes.apple.com/search";

// bigger than the 100px default the api hands back
const ARTWORK_SIZE = "300x300bb.jpg";

type Resolved = {
  title: string;
  artist: string;
  artworkUrl: string;
  durationSeconds: number;
};

async function resolve(seed: Seed): Promise<Resolved> {
  const params = new URLSearchParams({
    term: seed.query,
    entity: "song",
    limit: "3",
  });

  const fallback: Resolved = {
    title: seed.title,
    artist: seed.artist,
    artworkUrl: "",
    durationSeconds: 210,
  };

  try {
    const res = await fetch(`${ITUNES}?${params}`);
    if (!res.ok) {
      console.error(`lookup failed for ${seed.title}: ${res.status}`);
      return fallback;
    }

    const data = await res.json();
    const hit = data.results?.[0];
    if (!hit) {
      console.error(`no match for ${seed.title}`);
      return fallback;
    }

    return {
      title: seed.title,
      artist: seed.artist,
      artworkUrl: (hit.artworkUrl100 ?? "").replace(
        "100x100bb.jpg",
        ARTWORK_SIZE,
      ),
      durationSeconds: hit.trackTimeMillis
        ? Math.round(hit.trackTimeMillis / 1000)
        : fallback.durationSeconds,
    };
  } catch (err) {
    console.error(`error for ${seed.title}:`, err);
    return fallback;
  }
}

const songs: Resolved[] = [];

// serial, with a small gap — the itunes search api rate limits bursts
for (const seed of SEEDS) {
  const song = await resolve(seed);
  songs.push(song);
  console.log(
    `${song.artworkUrl ? "ok  " : "MISS"} ${song.title} — ${song.artist}`,
  );
  await new Promise((r) => setTimeout(r, 250));
}

const body = `// generated by scripts/fetch-artwork.ts — edit scripts/playlist.json instead

export interface Song {
  title: string;
  artist: string;
  /** cover art on apple's cdn; referenced, not redistributed */
  artworkUrl: string;
  durationSeconds: number;
}

/**
 * a fixed playlist. the widget picks a random track on each page load and
 * moves through the list from there, looping forever.
 */
export const SONGS = ${JSON.stringify(songs, null, 2)} as const satisfies ReadonlyArray<Song>;
`;

writeFileSync(join(ROOT, "src/utils/songs.ts"), body);
console.log(`\nwrote ${songs.length} songs`);
